### ISSUE TITLE
Make Scrolling Possible

### ISSUE THREAD

**Issue by elalemanyo** [mikejacobson/jquery-bootstrap-scrolling-tabs#16]
Hi,
Will be possible to make scrolling also possible?

Thanks!

**Comment by elalemanyo** [comment]
The idea is to make possible to have both: scrolling and arrows. For the moment I add some css to make .scrtabs-tabs-fixed-container scrollable:

```
.scrtabs-tabs-fixed-container {
   overflow-x: auto;
   overflow-y: hidden;
   display: -webkit-box;
   display: -moz-box;

   &::-webkit-scrollbar {
      display: none;
   }
}
```

Maybe add also `-webkit-overflow-scrolling: touch;`, but is not needed maybe.

The problem are now the arrows, I tried to use the scroll event on the container and run a `.scrollingTabs('refresh');`. But is not working als expected.

Do you have any idea how can do it better?

Thanks!

**Comment by mikejacobson** [comment]
v1.1.0 adds the option to allow swiping of the tabs on a touch screen. Details in the README here:
https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs#allowScrollbar

It's only really practical on WebKit browsers, though, because, to allow swiping, the horizontal scrollbar needs to be enabled, and only WebKit-based browsers allow the scrollbar to be hidden.

Not sure if that helps you or not, but it's available. :)

**Comment by elalemanyo** [comment]
Thanks! I will try with it.

**Comment by michalchovanak** [comment]
@mikejacobson you should add this to the next version, would be great.

**Comment by mikejacobson** [comment]
v2.0.0 implements better swiping functionality. I hope it works for you all. :smile:
