### ISSUE TITLE
Why rendering is visible?

### ISSUE THREAD

**Issue by alexeykuznec** [mikejacobson/jquery-bootstrap-scrolling-tabs#2]
When I refresh the page, I see the rendering like 3 stages:
1. I see standart bootstrap tabs in 2-3 lines;
2. I see 3 lines: left scrolling, movable container, right scrolling
3. I see all in 1 line

Can you make to show stage 3 at once? :) And your plugin will be the best :)

**Comment by mikejacobson** [comment]
Great suggestion! I agree--it does look a bit clunky on refresh.

I'll look into cleaning it up. I should have something within a few days.

**Comment by mikejacobson** [comment]
OK, v0.0.6 should fix this issue.

If your tabs are data-driven, they'll be hidden automatically during rendering so you don't need to do anything extra.

If they're _not_ data-driven and you're just wrapping markup, you'll have to add some styling to hide the `.nav-tabs` and `.tab-content` initially, then listen for event `ready.scrtabs` and unhide your `.tab-content` when the event fires (the `.nav-tabs` will be automatically unhidden by the plugin because it needs them unhidden). The [HTML-defined Tabs plunk](http://plnkr.co/edit/8i9i0qYKeggGzmR3Fv8X?p=preview) has this scenario set up.
