### ISSUE TITLE
Combination with scrollspy and auto focus on tabs while scrolling

### ISSUE THREAD

**Issue by sinasaeedi** [mikejacobson/jquery-bootstrap-scrolling-tabs#38]
Hello there.

I combined scrolling tabs with scrollspy. Everything works fine and when I scroll down, tabs will be selected automatically. But the problem is when the selected tab goes beyond the `navbar`.

![](http://uupload.ir/files/nbt_x1.png)
This is when I'm scrolling.

![](http://uupload.ir/files/lw3v_x2.png)
And this is when the selected tab is beyond the `navbar`.

If I continue scrolling, the selected tab goes completely out of sight.

Do you have a solution to auto focus on tabs while scrolling and showing whole tab?

Regards

**Comment by mikejacobson** [comment]
The plugin has a `scrollToActiveTab` method, described in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/#forcing-a-scroll-to-the-active-tab).

So you could attach a listener on scrollspy's `activate.bs.scrollspy` event and have it call the `scrollToActiveTab` method when a new item becomes activated by scrollspy:

```javascript
$('#myScrollspy').on('activate.bs.scrollspy', function () {
  $('.nav-tabs').scrollingTabs('scrollToActiveTab');
})
```
Would that give you what you need?

**Comment by sinasaeedi** [comment]
Thank you for noticing me to attach a listener on scrollspy's `activate.bs.scrollspy` event.
The problem now is `$('.nav-tabs').scrollingTabs('scrollToActiveTab');`. Acctually It doesn't do anything in my case. Not that nor `$('.nav-tabs').scrollingTabs('refresh');`.

This is my usage of `scrollingTabs`:

`
    $('.nav-tabs').scrollingTabs({
        enableSwiping: true,
        scrollToTabEdge: true,
        disableScrollArrowsOnFullyScrolled: true,
        widthMultiplier: 1,
        reverseScroll: true,
        enableRtlSupport: true,
        leftArrowContent: [
            '<div class="scrolling-tabs-arrow"><span class="fa fa-chevron-left"></span></div>'
        ].join(''),
        rightArrowContent: [
            '<div class="scrolling-tabs-arrow"><span class="fa fa-chevron-right"></span></div>'
        ].join('')
    });
`

**Comment by mikejacobson** [comment]
Would you be able to put together a plunk (maybe just fork one of the demo plunks from the README) that has your implementation? That would be helpful. I'm not sure why `scrollToActiveTab` and `refresh` wouldn't work.

**Comment by sinasaeedi** [comment]
OK thanks. I'll email a demo.
Please check your email.

**Comment by mikejacobson** [comment]
OK, I finally managed to get it working. This was a tricky one! There were a few things going on:

1. Since you're using Bootstrap 4, you need to attach the `activate.bs.scrollspy` event listener to the scroll element, not to the nav element. Bootstrap 3 triggered that event on the newly active tab `li` element but Bootstrap 4 triggers it on the scroll element (the one with `data-spy="scroll"`). I had to dig into the Bootstrap code to figure this out because their documentation doesn't make it clear. (I also submitted a PR to them to clarify their documentation.)

2. You need to get v2.1.1 of the `scrolling-tabs` plugin (which I just published). `scrollToActiveTab` was not working correctly for RTL so I needed to fix it.

3. You need to pass option `bootstrapVersion: 4` to the `scrolling-tabs` plugin if you're using Bootstrap 4 because 4 handles some things differently than 3 that I need to account for (e.g., attaching the `active` class to the tab's `li > a` element rather than the `li`).

[Here's your site.js](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/files/1347669/site.js.txt) updated with those changes.

**Comment by sinasaeedi** [comment]
@mikejacobson thank you very much.
Your support is awesome 👍

**Comment by tpicchetti** [comment]
Is there any site, to see this in action? I m looking for the same solution... cheers

**Comment by sinasaeedi** [comment]
> 
> 
> Is there any site, to see this in action? I m looking for the same solution... cheers

https://kb.tapfood.ir/Restaurant/22
