### ISSUE TITLE
boostrap4 nav-fill + scrolling-tabs

### ISSUE THREAD

**Issue by pehser** [mikejacobson/jquery-bootstrap-scrolling-tabs#39]
If you make a full-width tab through nav-fill, then immediately a scroll :(

**Comment by mikejacobson** [comment]
Are you using Bootstrap 4, I assume?

I was able to prevent that immediate scroll with a few small changes to how the plugin is typically initialized. Here's a plunk showing it working:
http://plnkr.co/edit/pvVvy21u9pqzN08OqUxs

It's a fork of the "HTML-Defined Tabs" plunk with some small changes to `st-demo.css` and `st-demo.js` (and, of course, `index.html` to use Bootstrap 4 and `nav-fill`).

Because Bootstrap 4 uses flexbox for the tabs, instead of defaulting `.nav-tabs` to `display: none` in `st-demo.css`, I default them to `visibility: hidden`. Then in `st-demo.js`, in the `ready.scrtabs` event handler, instead of using `.show()` to show them (which would set them to `display: block`), I set their `visibility` to `visible`.
