### ISSUE TITLE
Using with bootstrap 4 and problem in small screen

### ISSUE THREAD

**Issue by sinasaeedi** [mikejacobson/jquery-bootstrap-scrolling-tabs#41]
Hello there.

As you resolved `scrollToActiveTab`'s problem with bootstrap 4, now there is another issue.
When I see the page in a mobile sized screen, the scrolling-tab navbar resizes itself to a very small size.

![](http://uupload.ir/files/dt71_full.png)
The full size page works fine.

![](http://uupload.ir/files/t1v7_2.png)
The problem appears when a see the page in a mobile screen.

I tried to manipulate the CSS but no luck!

**Comment by mikejacobson** [comment]
Hi there,

Sorry for the delayed response. The problem is that Bootstrap 4 defaults the `flex-direction` of `.navbar-nav` to `column` until the viewport width is at least 1200px, at which point it sets it to `row`, which is what is needed for the tabs to display in the scroller.

So a quick fix would be to override that styling and force your `ul.nav-tabs` to have `flex-direction: row` regardless of viewport width. And I'll look into a more permanent fix to include in the plugin because I assume this will be an issue for others using Bootstrap 4 also.

**Comment by sinasaeedi** [comment]
Thank you man.

**Comment by mikejacobson** [comment]
v2.2.1 should fix this issue.

Note that you'll need to pass in option `bootstrapVersion: 4` if you're not already doing so.

I just added that info to the README. I realized I had added it to the usage info at the top of the .js file but never added it to the README.

**Comment by sinasaeedi** [comment]
Thanks a lot.
