### ISSUE TITLE
Title for Bootstrap Tooltips

### ISSUE THREAD

**Issue by genachka** [mikejacobson/jquery-bootstrap-scrolling-tabs#45]
I'd like to use the Data-Driven approach. I have a couple of use cases. One when I just went to set the `title` attribute while others I need to have Bootstrap Tooltips use the title attribute. How can I set the title attribute? Also, when I use the title attribute with Bootstrap tooltips I need to set HTML in the title attribute value my use cases. And if I'm using Bootstrap Tooltips, I need to include extra attributes on the `<li>` such as `data-template`, `data-trigger`, `data-html`, etc.

**Comment by mikejacobson** [comment]
Data-driven tabs currently don't support custom markup for the tabs but I could add that feature, similar to the `leftArrowContent` and `rightArrowContent` options that allow you to customize the arrow markup.

Would this approach work for you: I could create a new option called, say, `tabsLiContent` that would be an array of strings, each string being the markup for that tab's `li` element. Something like this:
```javascript
var tabs = [
  { paneId: 'tab00', title: 'Tab Index 0', tooltip: 'Tab 0', content: 'Tab Index 0 Content', active: true, disabled: false },
  { paneId: 'tab01', title: 'Tab Index 1', tooltip: 'Tab 1', content: 'Tab Index 1 Content', active: false, disabled: false },
  { paneId: 'tab02', title: 'Tab Index 2', tooltip: 'Tab 2', content: 'Tab Index 2 Content', active: false, disabled: false }
];

var tabsLiContent = tabs.map(function(tab) {
  return '<li role="presentation" title="' + tab.tooltip + '" data-trigger="hover"></li>';
});

$('#tabs-inside-here').scrollingTabs({
  tabs: tabs,
  tabsLiContent: tabsLiContent // <- new option will need to be created
});
```

**Comment by genachka** [comment]
Yes, that would work.

Though I realized there's another feature I would also need in conjunction with this. Since I don't use standard panes, but rather on the selected tab click need to have it run some javascript, I need a way to set the `<a>` value to for each tab. i.e. to call a javascript function with an identifier passed to it.

Perhaps it would look something like this:
```
var tabs = [
  { paneId: 'tab00', title: 'Tab Index 0', tooltip: 'Tab 0', href: '#', onClick: 'function("tab00")', content: 'Tab Index 0 Content', active: true, disabled: false },
  { paneId: 'tab01', title: 'Tab Index 1', tooltip: 'Tab 1', href: '#', onClick: 'function("tab01")', content: 'Tab Index 1 Content', active: false, disabled: false },
  { paneId: 'tab02', title: 'Tab Index 2', tooltip: 'Tab 2', href: '#', onClick: 'function("tab02")', content: 'Tab Index 2 Content', active: false, disabled: false }
];
```

**Comment by genachka** [comment]
@mikejacobson checking in, anything to test yet?

**Comment by mikejacobson** [comment]
Sorry, not yet. I started on it but then got busy with other things. I should have something in the next couple days. Sorry about that. Thanks for your patience.

**Comment by genachka** [comment]
Thanks for the update. Looking forward to trying out the changes.

**Comment by mikejacobson** [comment]
OK, v2.3.1 will hopefully provide the functionality you need.

I added the `tabsLiContent` functionality I proposed above. Details in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/#customTabLiContent).

And to provide the ability to attach custom click handlers to the anchor tags, I added a `tabsPostProcessors` option. Details in the README [here](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/#postProcessors).
It allows you to specify a post-processing function for each tab. When the tab's `li` and `a` elements are created, its function will be called and passed two arguments: the `$li` and `$a` jQuery elements that were just created for it. Having access to those elements will allow you to attach whatever event listeners you'd like. (It also makes the `tabsLiContent` feature somewhat unnecessary because you could just use these functions to also add your custom attributes to each `$li`, but I had already created the feature so I left it in.)

Here's a plunk demonstrating both new features:
http://plnkr.co/edit/ugJLMk7lmDCuZQziQ0k0

**Comment by genachka** [comment]
This is working out very well so far. Thank you!

`Having access to those elements will allow you to attach whatever event listeners you'd like. (It also makes the tabsLiContent feature somewhat unnecessary because you could just use these functions to also add your custom attributes to each $li, but I had already created the feature so I left it in.)`
Yeah, thought the same after I requested that, but I think having both in the end is very flexible should dev decide to use one or the other.
