### ISSUE TITLE
Changing scrtabs-tab-scroll-arrow width CSS impacts amount of scroll movement

### ISSUE THREAD

**Issue by 185driver** [mikejacobson/jquery-bootstrap-scrolling-tabs#52]
Is there a way to change the CSS width of the scroll tabs arrow and have scrolling-tabs compensate for the change? At present, scrolling-tabs appears to always expect a 20px wide left and right arrow when displayed. It seems to over-scroll on the left end and under-scroll on the right end.

Here's a codepen illustrating this behavior:
https://codepen.io/185driver/pen/KZeZOJ

Here's the CSS causing the issue:
```
.scrtabs-tab-scroll-arrow.scrtabs-tab-scroll-arrow-left {
  text-align: right;
  width: 60px; /* affects amount of scrollToActiveTab movement */
  padding-right: 6px;
}
.scrtabs-tab-scroll-arrow.scrtabs-tab-scroll-arrow-right {
  width: 48px; /* affects amount of scrollToActiveTab movement */
  padding-left: 6px;
}
```
This isn't an issue with scrolling-tabs, but I would like to be able to customize my arrow div widths. Thank you.

**Comment by mikejacobson** [comment]
Hmm, yeah, the `scrollToActiveTab` method is hardcoded to expect the arrow widths to be 20 when calculating the final position of the scrolling container. That's unfortunate. I really should be retrieving the widths dynamically.

If I make that fix, would that give you what you need? Will you just be adding some of your own CSS to override the plugin's and make the arrows your desired width?

**Comment by 185driver** [comment]
That would do it, though I suppose ideally the arrow icons would have their own wrapper so that the click area size could be controlled. At present, if `scrtabs-tab-scroll-arrow` is sized wider, the click area is all of the div rather than, say, a 36px or 48px square or something. I picture something like this:
```
<div class="scrtabs-tab-scroll-arrow scrtabs-tab-scroll-arrow-left">
  <button class="scrtabs-tab-scroll-arrow-left-btn" type="button">
    <i class="mdi mdi-chevron-left mdi-24px"></i>
  </button>
</div>
```
I'm most focused on the scrolling action through.

I do use custom CSS to adjust the styling of the arrows and their placement (via padding) to more closely match material design norms. Here's a codepen showing your plugin used with bootstrap-material-design: https://codepen.io/185driver/pen/zpaRqv. The arrows are positioned other than the default. My click area sizes are the full arrow divs. Thanks again.

**Comment by mikejacobson** [comment]
For custom arrow content, you can use the `leftArrowContent` and `rightArrowContent` options to specify the exact html you'd like for the arrows. However, as you mentioned, the way it works now, the entire arrow element would be clickable.

If you wanted just a child element within the arrow content to be clickable, I can think of two possible approaches:
1. I could add options like `leftArrowClickTarget` and `rightArrowClickTarget` that would allow you to specify css selectors to target the child elements you want. (I'm thinking the selectors would be relative from the tabs container, `.scrtabs-tab-container`.)

2. Within the custom arrow html, you could add an attribute like `scrtabs-click-target` to the element that should be the click target.

Here's a fork of your pen showing it working with option 1 (which I have in a branch of my repo right now):
https://codepen.io/mikejacobson/pen/RxzMPY

I just thought of option 2 as I was typing this, but that seems like a simpler solution to me, as it wouldn't require creating two new options, and it makes it very easy to specify your click targets.

What do you think about those options? Would either one work for you? Do you have a preference? Or do you have another suggestion?

**Comment by 185driver** [comment]
I had forgotten about being able to set custom arrow content html. Yes, that takes care of creating clickable areas via html and is wholly sufficient. Thank you.

One thing I noticed in your codepen fork is that the `disableScrollArrowsOnFullyScrolled` option isn't honored when custom arrow content is used. `.scrtabs-disable` does get applied to `.scrtabs-tab-scroll-arrow...` at the scroller ends, but not to its children, if they exist. Maybe I could listen for end of scroll and handle this myself, but it would be great if the plugin could handle it since it's listening for that already.

Your option 2 solution seems sufficient and is simpler, but I'm not sure about handling clicks. Because the plugin is already listening for a click anywhere on `.scrtabs-tab-scroll-arrow...`, my attempt to listen only within the targeted child element has no effect. Rather than create a custom class, and assuming custom arrow content markup with button elements (like your codepen fork), I tried this:
```
$('.scrtabs-tab-scroll-arrow').on('click', (e) => {
  if (!e.target.closest('button')) {
    // e.preventDefault type code needed here
    return;
  }
});
```
It works well in terms of only capturing button element clicks and ignoring the rest of the div, but it doesn't prevent the plugin's default arrow click event handler from running if the arrow div is clicked outside of the button.

How can I listen to what the plugin is listening to and conditionally prevent the default click handler from running so that only my target elements control firing the handler?

Your option 1 seems to take this piece into account, at least from what I can see. How about for option 2?

Thanks again.

**Comment by mikejacobson** [comment]
OK, I implemented option 2, where you add attribute `scrtabs-click-target` to the appropriate element inside your custom arrow content, and the plugin will only respond to clicks on that element, ignoring clicks on the parent `.scrtabs-tab-scroll-arrow` element.

It also handles the basic styling (e.g., `cursor: pointer` on the click target&mdash;and not the parent element&mdash;when enabled, and `cursor: default` when disabled). You'll probably want to add some of your own custom styling, though.

I updated the pen with the latest changes:
https://codepen.io/mikejacobson/pen/RxzMPY

Let me know if that provides what you need.

**Comment by 185driver** [comment]
That's it! It works nicely. I had some trouble at first with my own pen because I treated `scrtabs-click-target` as a class, not an attribute. That's a key piece to notice. Using the updated plugin, my pen at https://codepen.io/185driver/pen/BJXogN shows it all working with cleaned up CSS (I have red borders around the buttons for testing purposes).

The only issues left are the custom arrow content not getting `.scrtabs-disable` applied at the scroller ends (though the cursor does switch as it should), and of course the title issue which is the over- and -under scrolling of the tabs themselves on click due to the custom arrow div widths.

Thanks so much.

**Comment by mikejacobson** [comment]
I actually went back and forth about whether to have `scrtabs-click-target` as an attribute or a class. I decided on attribute since it's for functionality rather than styling, but having it a class is probably more intuitive and consistent since all the other `scrtabs-` pieces are classes. The fact that you expected it to be a class is a good indication that I should probably change it.

The custom arrow content is still getting `.scrtabs-disable` applied&mdash;it's being applied to the `scrtabs-tab-scroll-arrow` elements.

I did notice an issue in your pen, though, due to `d-flex justify-content-end` and `d-flex justify-content-start` being on the scroll arrow elements. Those classes apply `display: flex !important` on the arrows, which is overriding the `display: none` that the plugin applies to the arrows when they're not needed (due to the window being wide enough to accommodate all the tabs without scrolling). That's making the tabs container drop down to the next line so the tabs aren't visible.

Do you need those classes on there? When I remove them, things work fine for me. I could add `!important` to my `display: none`s, but I'd rather not if it's not necessary&mdash;I don't want to make it difficult/impossible to override if users have some need to do so.

And regarding the over- and under-scrolling, I did change it so the code is no longer using a hard-coded width for the arrows&mdash;it's retrieving them at run time. So it shouldn't be off by as much as it was before. But keep in mind that the final scrolling position can't be perfect. In the [README for the scrollToTabEdge option](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/#scrollToTabEdge), I mention that there's no way to guarantee the left *and* right edges will be full tabs, so that feature just makes sure the left side will be a full tab.

**Comment by mikejacobson** [comment]
OK, [v2.4.0](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/releases/tag/v2.4.0) adds the click-target feature.

I changed it from an attribute to a class, and I feel better about it&mdash;that attribute was feeling a little awkward to me.

I hope this works for you. Let me know if there are any problems. Your final result looks really good&mdash;nice work there. I like the material design style a lot.

Thanks for helping me improve my plugin!

Cheers,
Mike
