### ISSUE TITLE
Destroy method not working?

### ISSUE THREAD

**Issue by SmartFoxServer** [mikejacobson/jquery-bootstrap-scrolling-tabs#71]
In my application I'm creating a complex interface dynamically. The basic interface is made of these html elements:

```
<div id="znc-main">
	<div id="znc-tabNavigator">
		<ul class="nav nav-tabs" id="tabs" role="tablist"></ul>
		<div class="tab-content" id="tabPanels"></div>
	</div>
</div>
```

The tabs inside the `<ul>` and the panels inside the next `<div>` are created dynamically after loading a json which describes how many tabs are needed and what is their content (a complex forms in each tab).
After the html is generated, the Scrolling Tabs plugin is initialized and everything works fine.

```
<div id="znc-main">
	<div id="znc-tabNavigator">
		<div class="scrtabs-tab-container scrtabs-bootstrap4" style="visibility: visible;">
			<div class="scrtabs-tab-scroll-arrow scrtabs-tab-scroll-arrow-left scrtabs-disable" style="display: block;">
				<span class="fa fa-chevron-left"></span>
			</div>
			<div class="scrtabs-tabs-fixed-container" style="width: 727px;">
				<div class="scrtabs-tabs-movable-container" style="width: 1024.36px;">
					<ul class="nav nav-tabs" id="tabs" role="tablist">
						<li class="nav-item">
							<a class="nav-link active" id="tab-general" data-toggle="tab" href="#tabpane-general" role="tab" aria-controls="tabpane-general" aria-selected="true">General</a>
						</li>
						...
					</ul>
				</div>
			</div>
			<div class="scrtabs-tab-scroll-arrow scrtabs-tab-scroll-arrow-right" style="display: block;">
				<span class="fa fa-chevron-right"></span>
			</div>
		</div>

		<div class="tab-content" id="tabPanels">
			...
		</div>
	</div>
</div>
```

But then I need to destroy the interface (reverting it to the base html above) and generate it again after loading a different json (which will create different tabs).

The issue is that even after calling:
```$('#znc-tabNavigator > #tabs').scrollingTabs('destroy');```
the markup I'm wrapping is not restored, as stated in the documentation.

I also tried calling the destroy method in the following ways, but with no luck:
```
$('#znc-tabNavigator #tabs').scrollingTabs('destroy');
$('#znc-tabNavigator').scrollingTabs('destroy');
$('.scrtabs-tab-container').scrollingTabs('destroy');
```

Am I doing something wrong?
Thank you for your help.

**Comment by mikejacobson** [comment]
You would need to call `destroy` on the same element you originally called `.scrollingTabs()` on, so I would expect
```js
$('#znc-tabNavigator').scrollingTabs('destroy');
```
to work correctly because, based on your markup, it looks like that was the original target element. Are you doing anything that replaces the target element with another DOM element before you call `destroy`? That would break the connection.

I'd be able to help more if you could put together a plunk or something demonstrating the issue so I could dig a little deeper.

Here's a plunk showing `destroy` working properly:
http://plnkr.co/edit/9s7bfm8Ezt5LbVGlRp9F?p=preview

**Comment by SmartFoxServer** [comment]
Actually I'm initializing the tabs directly on the tabs container (id: tabs), in this way:
```
$('#znc-tabNavigator > #tabs').scrollingTabs({
	bootstrapVersion: 4,
	...
});
```
Using this approach (I guess wrong) the tabs work as expected, but not the _destroy_ method.

After your reply I tried to change the initialization using the external container (id: znc-tabNavigator), but unfortunately this is messing with the tabbed panels content, causing a number of errors. The content of panels is a very complex form, made of Custom Elements.
It seems when your plugin wraps the html, my elements are cloned (I guess moving them was not an option?) and this is causing the errors because my Custom Elements require data to be passed in their constructors.

Is there a chance to make the _destroy_ method work even when initialization occurs on the inner tabs container like I did originally?

Thank you for your help.

**Comment by SmartFoxServer** [comment]
PS: I also just tried to generate the tabs and panels content after initializing the Scrolling Tabs plugin. No errors are thrown anymore, but the panels doesn't show up when tabs are clicked. I guess the reason is that the plugin needs to "see" all the contents when it needs to wrap the html.

**Comment by SmartFoxServer** [comment]
I've put together a test case that shows the issue when the plugin is initialized on the external tab navigator as you suggested.

[Archive.zip](https://github.com/mikejacobson/jquery-bootstrap-scrolling-tabs/files/3594835/Archive.zip)

You will get an error related to my Custom Element trying to access a property on an undefined object. This is the error in the Chrome console:
```
Uncaught TypeError: Cannot read property 'text' of undefined
    at new MyElement (index.html:98)
    at Function.clone (jquery-3.3.1.min.js:2)
    at HTMLDivElement.<anonymous> (jquery-3.3.1.min.js:2)
    at jquery-3.3.1.min.js:2
    at Function.map (jquery-3.3.1.min.js:2)
    at w.fn.init.map (jquery-3.3.1.min.js:2)
    at w.fn.init.clone (jquery-3.3.1.min.js:2)
    at s (jquery.scrolling-tabs.min.js:8)
    at HTMLDivElement.<anonymous> (jquery.scrolling-tabs.min.js:8)
    at Function.each (jquery-3.3.1.min.js:2)
```

If you use the standard Bootstrap tabs, or if my Custom Element doesn't make use of constructor parameters, everything works fine. Of course none of those are valid options for me, so hopefully you can find a way to make this work (for example making the _destroy_ method work when the plugin is initialized on the tabs container, not the whole tab navigator).

**Comment by mikejacobson** [comment]
Sorry, I just re-read your use case and realized you're calling the plugin on already-defined tabs, not creating data-driven tabs using the plugin. So the plunk I created before was for the wrong use case.

Your selector for initializing the plugin (`'#znc-tabNavigator > #tabs'`) is correct&mdash;you are supposed to call the plugin on the `ul.nav-tabs` element.

And to destroy, you should be able to use the same selector but with the `>` removed since `#tabs` will no longer be a direct child of `#znc-tabNavigator`:
```js
$('#znc-tabNavigator #tabs').scrollingTabs('destroy');
```

But you mentioned above that you already tried that selector and it didn't work?

Here's a plunk showing it working with the index.html you sent in the zip file (click the Destroy button in the header to destroy):
http://plnkr.co/edit/MaqTYnk7J36G38d5u156?p=preview

**Comment by SmartFoxServer** [comment]
Thank you very much!
Changing the selector did the trick: now I can destroy the plugin and recreate new dynamic tabs without issues related to my Custom Elements.

**Comment by mikejacobson** [comment]
Stupendous! Glad to hear it's working now. 👍
